#!/usr/bin/make -f
# philippeg feb2014
# Generate csv files
# with persons who were assigned or commented on jira tickets, between a set of dates
# using the jira SQL interface, see: https://developer.atlassian.com/display/JIRADEV/Database+Schema 
#
.PHONY: login clean reallyclean test dotar test

##########################customise this section###############################################
#start date: yyyy-mm-dd 
startdate=2014-06-23
#end date: yyyy-mm-dd 
enddate=2014-06-26
#week number
wk=26
#jira projects, e.g. CA, CP, SCTX... 
projects=CA
team=xs-ring0
IssueVersion=Creedence
FixVersion=Creedence Outgoing
#priority=Blocker,Critical
#priorityDemote=Major,Minor,Trivial
priority=Major
priorityDemote=Minor,Trivial
########################end of custom section##################################################
#jira server params, read from .config file
host=$(lastword $(shell grep 'host' .config))
dbname=$(lastword $(shell grep 'dbname' .config))
username=$(lastword $(shell grep 'username' .config))
password=$(lastword $(shell grep 'password' .config))
#
ConnectToJira=psql --host=$(host) --dbname=$(dbname) --username=$(username)
setJiraPass=export PGPASSWORD=$(password)
#autogenerated name
suffix=$(team).$(priority)
priorityPsqlFormat=$(shell echo $(priority) | sed "s/\([^,]*\)/'\1'/g")
priorityDemotePsqlFormat=$(shell echo $(priorityDemote) | sed "s/\([^,]*\)/'\1'/g")
projectsPsqlFormat=$(shell echo $(projects) | sed "s/\([^,]*\)/'\1'/g")
#csv targets
inflowCSV=createdHistory.$(suffix).csv IssueAffectVersionHistory.$(suffix).csv TeamInHistory.$(suffix).csv promotePriorityHistory.$(suffix).csv reopenedHistory.$(suffix).csv
outflowCSV=resolvedHistory.$(suffix).csv TeamOutHistory.$(suffix).csv IssueFixVersionHistory.$(suffix).csv demotePriorityHistory.$(suffix).csv 
inflowreport=inflow.$(suffix).csv
outflowreport=outflow.$(suffix).csv
report=report.$(suffix).csv
###############################################################################################
all: $(inflowCSV) $(outflowCSV) $(inflowreport) $(outflowreport) $(report)
$(inflowreport): $(inflowCSV)
	cat $(inflowCSV)	> /tmp/tmpinflow.csv
	sort -r /tmp/tmpinflow.csv | ./rmdupIn.pl	>  $@
$(outflowreport): $(outflowCSV) $(inflowreport)
	cat $(outflowCSV)	> /tmp/tmpoutflow.csv
	sort -r /tmp/tmpoutflow.csv | ./rmdupOut.pl $(inflowreport) >  $@
$(report): $(inflowreport) $(outflowreport)
	@echo 'Generating report...'
	@echo 'REPORT from $(startdate) to $(enddate)'	| tee   $@
	@echo 'Team: $(team)'							| tee -a  $@
	@echo 'Release: $(IssueVersion)'				| tee -a  $@
	@echo 'Priority: $(priority)'					| tee -a  $@
	@cat $(inflowreport) $(outflowreport) | sort -r | tee -a  $@
	
login:
	$(setJiraPass) ; $(ConnectToJira)
clean: 
	rm -f inflow.csv outflow.csv $(inflowreport) $(outflowreport) $(inflowCSV) $(outflowCSV)
reallyclean:
	rm -f *.csv
createdHistory.$(suffix).csv: createdHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"   --variable=LOG="C+" \
	-f $< | uniq | tee   $@
IssueFixVersionHistory.$(suffix).csv: IssueFixVersionHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=PRIORITY="$(priorityPsqlFormat)" --variable=LOG="V-" \
	--variable=FIXVERSION="$(FixVersion)" \
	-f $< | uniq | tee   $@
IssueAffectVersionHistory.$(suffix).csv: IssueAffectVersionHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=PRIORITY="$(priorityPsqlFormat)" --variable=LOG="V+" \
	--variable=AFFECTVERSION="$(IssueVersion)" \
	-f $< | uniq | tee   $@
promotePriorityHistory.$(suffix).csv: priorityHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"  --variable=LOG="P+" \
	-f $< | uniq | tee   $@
demotePriorityHistory.$(suffix).csv: priorityHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityDemotePsqlFormat)"  --variable=LOG="P-" \
	-f $< | uniq | tee   $@
reopenedHistory.$(suffix).csv: statusHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'"  --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"   --variable=LOG="O+" \
	--variable=STATUS="'Resolved','Closed'" \
	-f $< | uniq | tee   $@
TeamInHistory.$(suffix).csv: TeamInHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"   --variable=LOG="T+" \
	-f $< | uniq | tee   $@
TeamOutHistory.$(suffix).csv: TeamOutHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"   --variable=LOG="T-" \
	-f $< | uniq | tee   $@
resolvedHistory.$(suffix).csv: resolvedHistory.sql
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"   --variable=LOG="R-" \
	-f $< | uniq | tee   $@
test:
	$(setJiraPass) ; $(ConnectToJira) \
	--field-separator="," --no-align --tuples-only \
	--variable=STARTDATE=$(startdate) --variable=ENDDATE=$(enddate) \
	--variable=TEAM="'$(team)'" --variable=PROJECTS="$(projectsPsqlFormat)" \
	--variable=RELIN="$(IssueVersion)" --variable=RELEXCL="$(FixVersion)" \
	--variable=PRIORITY="$(priorityPsqlFormat)"   --variable=LOG="C+" \
	-f test.sql | uniq | tee test.csv










